---
- name: Check if keycloak is running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod  
    namespace: "{{ keycloak_namespace }}"
  register: keycloak_resources

- name: Install keycloak
  when: keycloak_resources.resources | length <= 0
  block:
    - name: Add bitnami chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: create /tmp/keycloak-values.yml
      template:
        src: keycloak-values.yml.j2
        dest: /tmp/keycloak-values.yml

    - name: Install keycloak
      kubernetes.core.helm:
        name: keycloak
        chart_ref: bitnami/keycloak
        force: true
        release_namespace: "{{ keycloak_namespace }}"
        create_namespace: true
        values_files:
          - /tmp/keycloak-values.yml
