---
- name: Install Sealed Secrets
  block:
    - name: Add sealed secrets chart repo
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: "https://bitnami-labs.github.io/sealed-secrets"

    - name: Install sealed-secrets
      kubernetes.core.helm:
        name: sealed-secrets
        chart_ref: sealed-secrets/sealed-secrets
        wait: true
        release_namespace: kube-system
