---
- name: Install Promethues
  block:
    - name: Add prometheus chart repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Generate hashed password using openssl
      shell: htpasswd -bnBC 10 '' {{ prometheus_basic_auth_password }} | tr -d ':\n'
      register: hashed_password

    - name: Create Basic Auth string
      set_fact:
        basic_auth_string: "{{ prometheus_basic_auth_user }}:{{ prometheus_basic_auth_password }}"

    - name: Encode Basic Auth string to Base64
      set_fact:
        basic_auth_encoded: "{{ basic_auth_string | b64encode }}"

    - name: create /tmp/prometheus-values.yml
      template:
        src: prometheus-values.yml.j2
        dest: /tmp/prometheus-values.yml

    - name: Install prometheus
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: "{{ monitoring_namespace }}"
        create_namespace: true
        values_files:
          - /tmp/prometheus-values.yml 
    
        
