---
- name: Check if cert-manager is running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod  
    namespace: "{{ cert_manager_namespace }}"
  register: cert_manager_resources

- name: Install cert-manager
  when: cert_manager_resources.resources | length <= 0
  block:
    - name: Add cert-manager chart repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        chart_version: v1.15.3
        wait: true
        release_namespace: "{{ cert_manager_namespace }}"
        create_namespace: true
        values:
          crds:
            enabled: true

    - name: Configure cluster-issuer.yml file
      template:
        src: cluster-issuer.yml.j2
        dest: /tmp/cluster-issuer.yml

    - name: Install ClusterIssuer
      shell: kubectl apply -f /tmp/cluster-issuer.yml -n {{ cert_manager_namespace }} 
