---
- name: Check if crictl is running
  shell: crictl version
  ignore_errors: true
  tags: 
    - install
  register: crictl_check

- name: Install k8s
  tags: 
    - install
  when: crictl_check.rc != 0
  block:
    - name: Install packages needed to use the Kubernetes apt repository
      apt:
        update_cache: true
        name:
          - apt-transport-https 
          - ca-certificates 
          - curl 
          - gpg
          - gnupg2 
          - software-properties-common

    - name: Download Kubernetes GPG key and save it
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'

    - name: Dearmor the GPG key
      shell:
        cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg < /tmp/kubernetes-release.key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add k8s apt repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        state: present

    - name: Install packages needed to use the Kubernetes
      apt:
        update_cache: true
        name:
          - kubelet 
          - kubeadm 
          - kubectl

    - name: Hold kubeadm, kubelet, kubeadm
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet 
        - kubeadm 
        - kubectl

    - name: enable kubelet
      systemd_service:
        name: kubelet
        enabled: true
        state: started

    - name: create /etc/crictl.yaml
      copy:
        src: crictl.yaml
        dest: /etc/crictl.yaml
