apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "showcase.fullname" . }}
  labels: 
    {{- include "showcase.labels" . | nindent 4}}
data:
  githubUsername: msamec
  githubRepo: showcase
