{{- $fullName := include "showcase.fullname" . -}}
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: {{ .Values.app.image.ghcrSecretName }}
  labels: 
    {{- include "showcase.labels" . | nindent 4}}
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson | quote}}
