---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ include "showcase.fullname" . }}
spec:
  encryptedData:
    githubToken: AgAtP3b0UOT5zV4K4VnXFTEjb0bduNwXuAahGvKke7/7oYvEHLwZKGyEadddbcj17mF6wI8rei8o8gy+cbtY6YzqaYZSAqIG9BYiwy8vAbcQpzG1p2b+zxisgeVOMdoFbk9lOt5No4b/DfXAW7cOBboZ/vSMpHvlCilGIwic3rkypol79wb99hBALA37teWzesDJFX4TCwY7CJcjhQZEm467AEHBqAPmadP+dgVUlqXboIKMqtmoj4HXws64g6vpGjUDIAo/wGeynlc4izIXIEyMlpUKIoyhkEXkrfIYd9xK4v8iOL6OHcAbxrMI5wDnz3ythZEzqxNkNFP9CqyiA3cfj+Y41+K0zc0wanebbzovTa+jMlnwOLgYV/LdoOJRMphnINIUiKj6oSKoxYBtE03aCiWfNNPqkwyzX6Sbi+Iaf2i5rQ44hPCLQKAJOPrq8bH9d8cE1MC/txAQpl0ihzMdrRmoFaCzwC51vFe1VAuq6RIp/tpYK1I11YH8mNJ6xV++BJXVR21K4sI/P/B9EjVlsqA/wmv5BuSe8pwekLZMhdLxC2++m8SFZYZTtXDCClh3xRMHrHN5CGZwHV05vMEBof3VU01KqSorS4fbK9aLPirpPyFii3kiSjKrXGjlnSgSVppzT59qnrgsatnoPSqkehWlK/j/15HVKzpLwPztnS3ZFt567QLFZXLl0f0etB8siaFSLfRJPXAF/1DPbGK1DJ19Ge1JN1FrCd8tlw595fmNJ0w8SLY5CWddxgHgc/NkCan+aUjVOcJMsbW+mCjg9/tuuHQudQowEs3+MLcUzhkTA2PQ13Z0wz9flb7bfogc5v96/g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ include "showcase.fullname" . }}
