---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ include "showcase.fullname" . }}
spec:
  encryptedData:
    githubToken: AgAWFUDhrsH6yCiuT8bg2yCELaxiA1NeXRMX3qCtLbW4OmcGyqseKyTZo9mmiK099N6NFuPDn9Z0IAphWcJ7tc6UHKVWa2eA2MJscye4dH06RfkvoqETND6x64eWunJYhfLOKS/VNTNP+RAg1Zn/qfdkwNZfGSt8mM/F4OqZIZlb7Igx1DNVldV9S2N00hDcQMtEw4H0+tkOt4nzSk6M6xNj5GDwUH6im8LSWbfhnXGCntNLSNWZ3/OCyVbwGpriP6504ear7vViZV82zx0LgPH+93/a52SLWF/utnF+zRa7hFZq6pIcRJ0fkKhGwjNzNiggxADWw/CJU8FxSMLe/W+14OED3+VyogR60V+FsvUwJbM18c0HEuIyTnisFpI+RP8+hyrj9wBADP6H2dPKyavEiajW8waHLE1tnzLGtWiI0e9zruZ93tDz9oqyGHTqLfUBQXjZp+1sbUuwiUwqJY1/4qTlQ2XUGtyOLA44JGEMZZEpxaIzbkvCa//0kYiJTClvQSNI3z90c5Bzr5jtuVxztpD4hj1brQaU7cUhs0JFrHYldNsMVDE347tbw7R6Evg6UFMiqqptGJWklifvqozmOWx6jY9ziJ2MgRb9ATB7y46JXHE4OyxOfG5md9tbkSOPooU+ReAUrTnTAwjqnWv+mb5BW3kjBKJNBcWxY5MGHPTZOyZdlZdwh4wOsis+0gT8kgA7OCav7/trKzTISkwXBO5x9Sl3p2Khn1CL+f3nD3DVtgIC3mdc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ include "showcase.fullname" . }}
