---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ include "showcase.fullname" . }}
spec:
  encryptedData:
    githubToken: AgCSDYVSaXnS/yLkIZMBaUhtXPHeo155ZM3N3ZS/jTc5ysgckvcbtBLtXGs94LHr5uxsQDYv0I3m89/+qxbocar8duWMk/DulmeFi/xWfuaJnlw2D2xA9BBCm0ON7kc37Lz9jd/vOVYRTO5gkqHAvfnMqVx3VeTqGWgy3FPpZMS9fEvUtIyGXbdmWr+0EDvnNb4zbXlicoSxK3PFDUy1wAjQuS50Q81RlL4d9ujPSs2c3ciYRUyYSY3Nm5Hbzh1faVEMRfsJqgoU1csW5eJti4KMvHhbMq3p99De8MCbKtHK1C28b8XEkFrTocZ1bjRYt+axCl2/5KSeYI2IEQEg6T0wev951YaeAKV7vqJPo19k2OaVEYDn9pnHRl6M3ZD3CTAPyMFnKBi0m1v0V1t8vXxMuYD+1zWBuNr8lkxO8MBC85GWsfVQSVSV42ZzZI0MthWuNSiVYnvs8KiUrQSmKiLfBSsrHOLkZWCG6RHyNeTQ+ao90kQaAP5w9RLzaNDiKRQBZIoSiefH3xCny8l0E3IWdWofUb02gg68baKiC2pLUPS9sCylFNmS+EDpgbmKyG9cM73CSPQlfOknSP2wPqPfdFv0qodyCmAMiUNblgfx9Mg6q6VdDTlDyTunZt1CyDI5pvnBWqpPWWhMoEkdN/3bAFApJucDiB2ofV87crUkZZnvgenC2GCGNF83x/9JZ/w/wZWC0Yugy/Y9w7A9EFkoJBMFMqyVQZwl3J5WNc98ZMH0eR6brEaD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ include "showcase.fullname" . }}
    type: Opaque
