---
- name: Run apt-get update and install docker packages
  apt:
    update_cache: true
    name:
      - containerd

- name: Create a directory if it does not exist
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate containerd config 
  shell: containerd config default | tee /etc/containerd/config.toml

- name: configuring the systemd cgroup driver for Containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup = false'
    replace: '\1SystemdCgroup = true'
  notify: restart containerd
