---
- fail:
    msg: "OS should be Ubuntu 22.04, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '22.04'

- name: disable SWAP (Kubeadm requirement)
  shell: swapoff -a

- name: disable SWAP in fstab (Kubeadm requirement)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Enable modules
  modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Update kernel params
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop: 
    - { name: net.ipv4.ip_forward, value: 1}
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - { name: net.bridge.bridge-nf-call-iptables, value: 1}

- name: Install packages
  apt:
    update_cache: true
    name:
      - git 
      - python3-dev 
      - python3-pip
      - libffi-dev 
      - gcc 
      - libssl-dev
      - apache2-utils

- name: Install python package
  pip:
    name:
      - kubernetes

- name: Install helm if not exists
  unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm
